package main

import (
	"bufio"
	"fmt"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type SchemaConfig struct {
	Name     string
	Path     string
	Output   string
	MigTable string
}

var schemas = []SchemaConfig{
	{
		Name:     "authgear",
		Path:     "cmd/authgear/cmd/cmddatabase/migrations/authgear",
		Output:   ".local/database/authgear.sql",
		MigTable: "_auth_migration",
	},
	{
		Name:     "portal",
		Path:     "cmd/portal/cmd/cmddatabase/migrations/portal",
		Output:   ".local/database/portal.sql",
		MigTable: "_portal_migration",
	},
	{
		Name:     "audit",
		Path:     "cmd/authgear/cmd/cmdaudit/migrations/audit",
		Output:   ".local/database/audit.sql",
		MigTable: "_audit_migration",
	},
	{
		Name:     "search",
		Path:     "cmd/authgear/cmd/cmdsearch/migrations/search",
		Output:   ".local/database/search.sql",
		MigTable: "_search_migration",
	},
	{
		Name:     "images",
		Path:     "cmd/authgear/cmd/cmdimages/cmddatabase/migrations/images",
		Output:   ".local/database/images.sql",
		MigTable: "_images_migration",
	},
}

func main() {
	outputDir := ".local/database"
	err := os.MkdirAll(outputDir, 0755)
	if err != nil {
		log.Fatalf("Failed to create output directory: %v", err)
	}

	var allSchemas []string

	for _, schema := range schemas {
		fmt.Printf("Processing %s schema...\n", schema.Name)
		sql, err := generateSchema(schema)
		if err != nil {
			log.Fatalf("Failed to generate %s schema: %v", schema.Name, err)
		}

		outputPath := schema.Output
		err = os.WriteFile(outputPath, []byte(sql), 0644)
		if err != nil {
			log.Fatalf("Failed to write %s: %v", outputPath, err)
		}

		allSchemas = append(allSchemas, sql)
		fmt.Printf("Generated %s\n", outputPath)
	}

	// Generate combined schema
	combinedSQL := generateCombinedSchema(allSchemas)
	combinedPath := filepath.Join(outputDir, "schema.sql")
	err = os.WriteFile(combinedPath, []byte(combinedSQL), 0644)
	if err != nil {
		log.Fatalf("Failed to write combined schema: %v", err)
	}
	fmt.Printf("Generated %s\n", combinedPath)

	// Generate README
	readme := generateREADME()
	readmePath := filepath.Join(outputDir, "README.md")
	err = os.WriteFile(readmePath, []byte(readme), 0644)
	if err != nil {
		log.Fatalf("Failed to write README: %v", err)
	}
	fmt.Printf("Generated %s\n", readmePath)

	fmt.Println("\nAll database schemas generated successfully!")
}

func generateSchema(config SchemaConfig) (string, error) {
	var files []string

	err := filepath.WalkDir(config.Path, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".sql") {
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		return "", fmt.Errorf("failed to walk directory: %w", err)
	}

	// Sort files by timestamp (filename format: YYYYMMDDHHMMSS-name.sql)
	sort.Strings(files)

	var builder strings.Builder
	builder.WriteString(fmt.Sprintf("-- %s Schema\n", strings.ToUpper(config.Name)))
	builder.WriteString(fmt.Sprintf("-- Generated from migration files in: %s\n", config.Path))
	builder.WriteString(fmt.Sprintf("-- Migration table: %s\n", config.MigTable))
	builder.WriteString("--\n")
	builder.WriteString("-- This file is generated automatically from migration files.\n")
	builder.WriteString("-- DO NOT edit this file directly. Edit migration files instead.\n")
	builder.WriteString("--\n\n")

	for _, file := range files {
		content, err := os.ReadFile(file)
		if err != nil {
			return "", fmt.Errorf("failed to read %s: %w", file, err)
		}

		upSQL := extractUpMigration(string(content))
		if upSQL != "" {
			fileName := filepath.Base(file)
			builder.WriteString(fmt.Sprintf("-- Migration: %s\n", fileName))
			builder.WriteString(upSQL)
			builder.WriteString("\n\n")
		}
	}

	return builder.String(), nil
}

func extractUpMigration(content string) string {
	var builder strings.Builder
	scanner := bufio.NewScanner(strings.NewReader(content))
	inUp := false
	inDown := false

	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		if strings.HasPrefix(trimmed, "-- +migrate Up") {
			inUp = true
			inDown = false
			continue
		}

		if strings.HasPrefix(trimmed, "-- +migrate Down") {
			inUp = false
			inDown = true
			continue
		}

		if inUp && !inDown {
			builder.WriteString(line)
			builder.WriteString("\n")
		}
	}

	return strings.TrimSpace(builder.String())
}

func generateCombinedSchema(schemas []string) string {
	var builder strings.Builder
	builder.WriteString("-- Complete Database Schema\n")
	builder.WriteString("-- Generated from all migration files\n")
	builder.WriteString("--\n")
	builder.WriteString("-- This file contains all database schemas combined.\n")
	builder.WriteString("-- DO NOT use this file to create database directly.\n")
	builder.WriteString("-- Use migration tools instead.\n")
	builder.WriteString("--\n\n")

	for i, schema := range schemas {
		if i > 0 {
			builder.WriteString("\n-- ============================================\n\n")
		}
		builder.WriteString(schema)
		builder.WriteString("\n")
	}

	return builder.String()
}

func generateREADME() string {
	return `# 数据库Schema文档

本目录包含从数据库迁移文件生成的完整数据库schema。

## Schema文件

1. **authgear.sql** - Authgear核心认证schema
   - 来源: cmd/authgear/cmd/cmddatabase/migrations/authgear/
   - 包含: 用户、身份、认证器等核心表

2. **portal.sql** - Portal管理schema
   - 来源: cmd/portal/cmd/cmddatabase/migrations/portal/
   - 包含: 配置、域名、协作者、订阅等表

3. **audit.sql** - 审计日志schema
   - 来源: cmd/authgear/cmd/cmdaudit/migrations/audit/
   - 包含: 审计日志表

4. **search.sql** - 搜索schema
   - 来源: cmd/authgear/cmd/cmdsearch/migrations/search/
   - 包含: 用户搜索表

5. **images.sql** - 图片文件schema
   - 来源: cmd/authgear/cmd/cmdimages/cmddatabase/migrations/images/
   - 包含: 图片文件表

6. **schema.sql** - 完整schema（所有schema合并）

## 生成方式

这些文件是通过运行以下命令自动生成的：

` + "```bash\n" + `go run scripts/generateschema/main.go
` + "```\n\n" + `## 注意事项

1. **不要直接编辑这些SQL文件** - 它们是从迁移文件自动生成的
2. **不要使用这些文件创建数据库** - 应使用迁移工具（go run cmd/authgear/cmd/main.go database migrate up）
3. **这些文件主要用于文档和参考** - 了解数据库结构

## 迁移文件位置

- Authgear: cmd/authgear/cmd/cmddatabase/migrations/authgear/
- Portal: cmd/portal/cmd/cmddatabase/migrations/portal/
- Audit: cmd/authgear/cmd/cmdaudit/migrations/audit/
- Search: cmd/authgear/cmd/cmdsearch/migrations/search/
- Images: cmd/authgear/cmd/cmdimages/cmddatabase/migrations/images/

## 更新Schema

当迁移文件更新后，重新运行生成脚本：

` + "```bash\n" + `go run scripts/generateschema/main.go
` + "```\n\n" + `---

**最后更新**: 自动生成
`
}
