# Docsify documentation site
# Run `make start` to serve docs at http://localhost:3000

PORT ?= 3000

.PHONY: start
start:
	@echo "Starting Authgear Docs at http://localhost:$(PORT)"
	@echo "Press Ctrl+C to stop"
	python3 -m http.server $(PORT)
